### ISSUE TITLE
Missing type="rss" label in opml file

### ISSUE THREAD

**Issue by zaowen** [funkaoshi/osr-opml#1]
It looks like all of the links in your opml are rss feeds, most even end in an rss query string. Would it be possible to add the type property to the python script and rebuild the opml? 
I know opml isn't the most well defined standard but some of the other opml files I've found do have it.

**Comment by funkaoshi** [comment]
Sorry I 100% missed this issue ... for 4 years! This seems easy enough to do once I find an example of an OPML feed that does this.

**Comment by funkaoshi** [comment]
This should be resolved @zaowen!
